In [1]:
import pandas as pd

In [2]:
games = pd.read_csv("NCAA_Data_Working.csv", index_col=0)

In [3]:
games = games.reset_index()

In [4]:
games

,g,date,venue,opp,w/l,tm,opp.1,fg,fga,fg%,...,ft%.1,orb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,season,team
0,1,2023-11-06,@,Oklahoma State,W,64.0,59.0,26.0,57.0,0.456,...,0.400,6.0,32.0,13.0,9.0,2.0,12.0,16.0,2024,abilene christian
1,2,2023-11-10,@,NC State,L,64.0,84.0,20.0,57.0,0.351,...,0.833,12.0,34.0,12.0,4.0,3.0,7.0,20.0,2024,abilene christian
2,3,2023-11-14,NaN,Prairie View,L,74.0,79.0,23.0,60.0,0.383,...,0.971,8.0,34.0,7.0,8.0,5.0,14.0,23.0,2024,abilene christian
3,4,2023-11-17,N,San Jose State,W,77.0,71.0,25.0,59.0,0.424,...,0.583,9.0,35.0,13.0,4.0,3.0,6.0,18.0,2024,abilene christian
4,5,2023-11-19,N,Fordham,W,59.0,45.0,22.0,55.0,0.400,...,0.571,16.0,41.0,3.0,5.0,3.0,19.0,16.0,2024,abilene christian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23980,30,2023-02-21,@,Robert Morris,L,64.0,83.0,23.0,47.0,0.489,...,0.778,4.0,24.0,14.0,6.0,7.0,12.0,17.0,2023,youngstown state
23981,31,2023-02-25,@,IU Indianapolis,W,93.0,79.0,34.0,59.0,0.576,...,0.636,8.0,25.0,15.0,4.0,4.0,12.0,18.0,2023,youngstown state
23982,32,2023-03-02,NaN,Detroit Mercy,W,71.0,66.0,24.0,55.0,0.436,...,0.857,13.0,36.0,11.0,5.0,3.0,13.0,21.0,2023,youngstown state
23983,33,2023-03-06,N,Northern Kentucky,L,63.0,75.0,24.0,53.0,0.453,...,0.737,16.0,32.0,6.0,6.0,2.0,2.0,18.0,2023,youngstown state
23984,34,2023-03-15,NaN,Oklahoma State,L,64.0,69.0,22.0,62.0,0.355,...,0.867,15.0,45.0,13.0,3.0,6.0,9.0,15.0,2023,youngstown state

In [5]:
games["team"].value_counts()

team
connecticut             79
san diego state         76
indiana state           75
north carolina state    75
houston                 74
                        ..
dartmouth               56
harvard                 55
le moyne                33
st francis ny           30
hartford                28
Name: count, Length: 364, dtype: int64

In [6]:
games.dtypes

g                        int64
date                    object
venue                   object
opp                     object
w/l                     object
tm                     float64
opp.1                  float64
fg                     float64
fga                    float64
fg%                    float64
3p                     float64
3pa                    float64
3p%                    float64
ft                     float64
fta                    float64
ft%                    float64
orb                    float64
trb                    float64
ast                    float64
stl                    float64
blk                    float64
tov                    float64
pf                     float64
unnamed: 23_level_1    float64
fg.1                   float64
fga.1                  float64
fg%.1                  float64
3p.1                   float64
3pa.1                  float64
3p%.1                  float64
ft.1                   float64
fta.1                  float64
ft%.1                  float64
orb.1                  float64
trb.1                  float64
ast.1                  float64
stl.1                  float64
blk.1                  float64
tov.1                  float64
pf.1                   float64
season                   int64
team                    object
dtype: object

In [7]:
games["date"] = pd.to_datetime(games["date"]) # converting the date col to datetime type

In [8]:
games["venue_code"] = games["venue"].astype("category").cat.codes #away = 0, home = -1, neutral = 1

In [9]:
games

,g,date,venue,opp,w/l,tm,opp.1,fg,fga,fg%,...,orb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,season,team,venue_code
0,1,2023-11-06,@,Oklahoma State,W,64.0,59.0,26.0,57.0,0.456,...,6.0,32.0,13.0,9.0,2.0,12.0,16.0,2024,abilene christian,0
1,2,2023-11-10,@,NC State,L,64.0,84.0,20.0,57.0,0.351,...,12.0,34.0,12.0,4.0,3.0,7.0,20.0,2024,abilene christian,0
2,3,2023-11-14,NaN,Prairie View,L,74.0,79.0,23.0,60.0,0.383,...,8.0,34.0,7.0,8.0,5.0,14.0,23.0,2024,abilene christian,-1
3,4,2023-11-17,N,San Jose State,W,77.0,71.0,25.0,59.0,0.424,...,9.0,35.0,13.0,4.0,3.0,6.0,18.0,2024,abilene christian,1
4,5,2023-11-19,N,Fordham,W,59.0,45.0,22.0,55.0,0.400,...,16.0,41.0,3.0,5.0,3.0,19.0,16.0,2024,abilene christian,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23980,30,2023-02-21,@,Robert Morris,L,64.0,83.0,23.0,47.0,0.489,...,4.0,24.0,14.0,6.0,7.0,12.0,17.0,2023,youngstown state,0
23981,31,2023-02-25,@,IU Indianapolis,W,93.0,79.0,34.0,59.0,0.576,...,8.0,25.0,15.0,4.0,4.0,12.0,18.0,2023,youngstown state,0
23982,32,2023-03-02,NaN,Detroit Mercy,W,71.0,66.0,24.0,55.0,0.436,...,13.0,36.0,11.0,5.0,3.0,13.0,21.0,2023,youngstown state,-1
23983,33,2023-03-06,N,Northern Kentucky,L,63.0,75.0,24.0,53.0,0.453,...,16.0,32.0,6.0,6.0,2.0,2.0,18.0,2023,youngstown state,1
23984,34,2023-03-15,NaN,Oklahoma State,L,64.0,69.0,22.0,62.0,0.355,...,15.0,45.0,13.0,3.0,6.0,9.0,15.0,2023,youngstown state,-1

In [10]:
games.dtypes

g                               int64
date                   datetime64[ns]
venue                          object
opp                            object
w/l                            object
tm                            float64
opp.1                         float64
fg                            float64
fga                           float64
fg%                           float64
3p                            float64
3pa                           float64
3p%                           float64
ft                            float64
fta                           float64
ft%                           float64
orb                           float64
trb                           float64
ast                           float64
stl                           float64
blk                           float64
tov                           float64
pf                            float64
unnamed: 23_level_1           float64
fg.1                          float64
fga.1                         float64
fg%.1                         float64
3p.1                          float64
3pa.1                         float64
3p%.1                         float64
ft.1                          float64
fta.1                         float64
ft%.1                         float64
orb.1                         float64
trb.1                         float64
ast.1                         float64
stl.1                         float64
blk.1                         float64
tov.1                         float64
pf.1                          float64
season                          int64
team                           object
venue_code                       int8
dtype: object

In [11]:
games["opp_code"] = games["opp"].astype("category").cat.codes # converting opponents to an opp code

In [12]:
games["day_code"] = games["date"].dt.dayofweek # converting day of week to usable data

In [13]:
nan_values = games["w/l"].isnull()

In [14]:
nan_values

0        False
1        False
2        False
3        False
4        False
         ...
23980    False
23981    False
23982    False
23983    False
23984    False
Name: w/l, Length: 23985, dtype: bool

In [15]:
import numpy as np

In [16]:
games["target"] = np.where(games["w/l"].str.startswith("W"), 1, 0) # converting wins/losses to usable data

In [17]:
games.dtypes

g                               int64
date                   datetime64[ns]
venue                          object
opp                            object
w/l                            object
tm                            float64
opp.1                         float64
fg                            float64
fga                           float64
fg%                           float64
3p                            float64
3pa                           float64
3p%                           float64
ft                            float64
fta                           float64
ft%                           float64
orb                           float64
trb                           float64
ast                           float64
stl                           float64
blk                           float64
tov                           float64
pf                            float64
unnamed: 23_level_1           float64
fg.1                          float64
fga.1                         float64
fg%.1                         float64
3p.1                          float64
3pa.1                         float64
3p%.1                         float64
ft.1                          float64
fta.1                         float64
ft%.1                         float64
orb.1                         float64
trb.1                         float64
ast.1                         float64
stl.1                         float64
blk.1                         float64
tov.1                         float64
pf.1                          float64
season                          int64
team                           object
venue_code                       int8
opp_code                        int16
day_code                        int32
target                          int64
dtype: object

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rf = RandomForestClassifier(n_estimators=200, min_samples_split=15, random_state=1)

In [20]:
train = games[games["date"] < '2023-05-01'] # train on old data

In [21]:
test = games[games["date"] > '2023-05-01'] # test training based model on newer data

In [22]:
predictors = ["venue_code", "opp_code", "day_code"] # initial predictors for model

In [23]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=15, n_estimators=200, random_state=1)

In [24]:
preds = rf.predict(test[predictors])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
acc = accuracy_score(test["target"], preds)

In [27]:
acc

0.6227689741451209

In [28]:
from sklearn.metrics import precision_score

In [29]:
precision_score(test["target"], preds)

0.6363065326633166

In [30]:
grouped_games = games.groupby("team")

In [31]:
group = grouped_games.get_group("abilene christian")

In [32]:
group

,g,date,venue,opp,w/l,tm,opp.1,fg,fga,fg%,...,stl.1,blk.1,tov.1,pf.1,season,team,venue_code,opp_code,day_code,target
0,1,2023-11-06,@,Oklahoma State,W,64.0,59.0,26.0,57.0,0.456,...,9.0,2.0,12.0,16.0,2024,abilene christian,0,520,0,1
1,2,2023-11-10,@,NC State,L,64.0,84.0,20.0,57.0,0.351,...,4.0,3.0,7.0,20.0,2024,abilene christian,0,462,4,0
2,3,2023-11-14,NaN,Prairie View,L,74.0,79.0,23.0,60.0,0.383,...,8.0,5.0,14.0,23.0,2024,abilene christian,-1,557,1,0
3,4,2023-11-17,N,San Jose State,W,77.0,71.0,25.0,59.0,0.424,...,4.0,3.0,6.0,18.0,2024,abilene christian,1,618,4,1
4,5,2023-11-19,N,Fordham,W,59.0,45.0,22.0,55.0,0.400,...,5.0,3.0,19.0,16.0,2024,abilene christian,1,229,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12017,28,2023-02-22,NaN,Stephen F. Austin,L (2 OT),87.0,91.0,27.0,71.0,0.380,...,6.0,5.0,17.0,28.0,2023,abilene christian,-1,676,2,0
12018,29,2023-02-25,NaN,Utah Valley,L,62.0,66.0,23.0,61.0,0.377,...,6.0,4.0,15.0,12.0,2023,abilene christian,-1,753,5,0
12019,30,2023-03-01,NaN,New Mexico State,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2023,abilene christian,-1,472,2,1
12020,31,2023-03-03,@,Sam Houston,L,54.0,72.0,15.0,47.0,0.319,...,3.0,2.0,10.0,22.0,2023,abilene christian,0,611,4,0
12021,32,2023-03-07,N,California Baptist,L,62.0,69.0,27.0,67.0,0.403,...,5.0,2.0,16.0,19.0,2023,abilene christian,1,96,1,0

In [33]:
def rolling_averages(group, cols, new_cols): #calculates rolling average of cols
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [34]:
cols = ["tm", "opp.1", "fg%", "fg%.1", "3p%", "3p%.1", "ft%", "ft%.1", "stl", "stl.1"] # new cols for predictors
new_cols = [f"{c}_rolling" for c in cols]

In [35]:
new_cols

['tm_rolling',
 'opp.1_rolling',
 'fg%_rolling',
 'fg%.1_rolling',
 '3p%_rolling',
 '3p%.1_rolling',
 'ft%_rolling',
 'ft%.1_rolling',
 'stl_rolling',
 'stl.1_rolling',
 'pf_rolling',
 'pf.1_rolling']

In [36]:
rolling_averages(group, cols, new_cols)

,g,date,venue,opp,w/l,tm,opp.1,fg,fga,fg%,...,fg%_rolling,fg%.1_rolling,3p%_rolling,3p%.1_rolling,ft%_rolling,ft%.1_rolling,stl_rolling,stl.1_rolling,pf_rolling,pf.1_rolling
11993,4,2022-11-21,N,Wright State,L,61.0,77.0,25.0,58.0,0.431,...,0.464000,0.409667,0.341333,0.251000,0.718667,0.698333,11.666667,8.666667,19.000000,18.666667
11994,5,2022-11-22,N,Weber State,L,67.0,77.0,26.0,53.0,0.491,...,0.473000,0.476333,0.352000,0.367667,0.668667,0.671000,12.333333,10.666667,21.000000,16.333333
11995,6,2022-11-23,N,UC-Riverside,L,65.0,76.0,22.0,60.0,0.367,...,0.508333,0.459000,0.380333,0.338000,0.572667,0.739667,11.000000,8.333333,20.000000,15.000000
11996,7,2022-11-27,@,Northern Arizona,W,92.0,82.0,34.0,60.0,0.567,...,0.429667,0.511000,0.379667,0.372000,0.574333,0.819000,8.333333,7.666667,21.000000,15.333333
11997,8,2022-11-30,NaN,North American,W,93.0,46.0,31.0,68.0,0.456,...,0.475000,0.472000,0.459000,0.372000,0.653000,0.850667,6.666667,4.666667,20.666667,16.666667
11998,9,2022-12-03,NaN,Arlington Baptist,W,88.0,42.0,36.0,67.0,0.537,...,0.463333,0.420667,0.409000,0.405000,0.727667,0.782000,9.333333,4.666667,20.333333,20.000000
11999,10,2022-12-06,@,Kansas State,L,64.0,81.0,25.0,55.0,0.455,...,0.520000,0.357667,0.418333,0.354000,0.735000,0.761000,11.333333,4.000000,19.333333,17.333333
12000,11,2022-12-10,NaN,East Texas A&M,W,83.0,64.0,28.0,55.0,0.509,...,0.482667,0.391667,0.355667,0.285667,0.717333,0.702667,11.333333,5.333333,19.000000,15.666667
12001,12,2022-12-17,@,Cal State Bakersfield,W,65.0,59.0,20.0,49.0,0.408,...,0.500333,0.439333,0.362667,0.247000,0.752667,0.709000,9.666667,5.333333,18.666667,14.666667
12002,13,2022-12-21,NaN,Howard Payne,W,113.0,52.0,44.0,79.0,0.557,...,0.457333,0.498000,0.414667,0.247000,0.713333,0.699333,7.333333,4.666667,18.333333,19.000000
12003,14,2022-12-29,@,Stephen F. Austin,L,68.0,75.0,28.0,61.0,0.459,...,0.491333,0.401667,0.415667,0.219333,0.679000,0.757667,9.666667,5.000000,18.000000,22.333333
12004,15,2022-12-31,NaN,Tarleton State,W,69.0,63.0,21.0,49.0,0.429,...,0.474667,0.406333,0.382333,0.225000,0.569000,0.740000,7.666667,6.333333,19.333333,21.666667
12005,16,2023-01-07,NaN,Southern Utah,L,72.0,74.0,25.0,63.0,0.397,...,0.481667,0.402667,0.328000,0.317667,0.578333,0.739000,8.666667,7.666667,19.333333,22.333333
12006,17,2023-01-11,@,Texas-Rio Grande Valley,L,86.0,103.0,29.0,72.0,0.403,...,0.428333,0.490000,0.271000,0.383333,0.716667,0.706333,8.000000,6.000000,21.333333,23.333333
12007,18,2023-01-14,@,Tarleton State,L,63.0,72.0,24.0,57.0,0.421,...,0.409667,0.556667,0.258667,0.443667,0.819000,0.715667,11.000000,5.000000,25.666667,25.000000
12008,19,2023-01-18,@,Utah Valley,L,54.0,84.0,21.0,70.0,0.300,...,0.407000,0.558667,0.242000,0.428667,0.741000,0.695667,10.333333,5.000000,28.000000,22.666667
12009,20,2023-01-21,NaN,UT Arlington,W,84.0,68.0,31.0,49.0,0.633,...,0.374667,0.550000,0.242000,0.418333,0.633000,0.730333,9.666667,5.666667,25.333333,20.333333
12010,21,2023-01-26,NaN,Grand Canyon,L,73.0,75.0,29.0,61.0,0.475,...,0.451333,0.475667,0.350333,0.419667,0.615667,0.727667,8.000000,5.666667,21.000000,17.333333
12011,22,2023-01-28,NaN,Utah Tech,W,81.0,76.0,27.0,57.0,0.474,...,0.469333,0.498000,0.373667,0.425000,0.633333,0.741667,8.666667,5.000000,19.666667,16.666667
12012,23,2023-02-01,@,Seattle,W,83.0,68.0,34.0,67.0,0.507,...,0.527333,0.490667,0.307000,0.473333,0.724333,0.714000,9.000000,5.333333,22.333333,19.333333
12013,24,2023-02-04,@,California Baptist,W,87.0,71.0,27.0,52.0,0.519,...,0.485333,0.478667,0.277667,0.423333,0.717000,0.666000,8.666667,4.666667,20.333333,19.000000
12014,25,2023-02-11,NaN,Sam Houston,L,62.0,77.0,21.0,54.0,0.389,...,0.500000,0.465667,0.350000,0.346333,0.834000,0.619333,8.000000,4.333333,20.333333,18.666667
12015,26,2023-02-15,@,New Mexico State,NaN,NaN,NaN,NaN,NaN,NaN,...,0.471667,0.479333,0.478333,0.330000,0.830333,0.638667,7.000000,4.000000,17.666667,15.000000
12019,30,2023-03-01,NaN,New Mexico State,NaN,NaN,NaN,NaN,NaN,NaN,...,0.405333,0.569667,0.318667,0.523667,0.785333,0.752667,8.333333,4.333333,20.000000,21.333333
1,2,2023-11-10,@,NC State,L,64.0,84.0,20.0,57.0,0.351,...,0.392667,0.447333,0.192667,0.380333,0.684333,0.528667,4.333333,5.666667,20.666667,19.000000
2,3,2023-11-14,NaN,Prairie View,L,74.0,79.0,23.0,60.0,0.383,...,0.403333,0.449000,0.224000,0.311333,0.669000,0.621000,4.666667,6.000000,20.666667,18.333333
3,4,2023-11-17,N,San Jose State,W,77.0,71.0,25.0,59.0,0.424,...,0.396667,0.436000,0.278333,0.296667,0.711000,0.734667,5.333333,7.000000,20.666667,19.666667
4,5,2023-11-19,N,Fordham,W,59.0,45.0,22.0,55.0,0.400,...,0.386000,0.452000,0.341333,0.331000,0.755333,0.795667,4.333333,5.333333,19.333333,20.333333
5,6,2023-11-20,N,Missouri State,L,69.0,87.0,25.0,59.0,0.424,...,0.402333,0.394667,0.326667,0.267667,0.756000,0.708333,6.666667,5.666667,19.333333,19.000000
6,7,2023-11-29,@,UT Arlington,L,71.0,86.0,25.0,55.0,0.455,...,0.416000,0.444000,0.385000,0.264000,0.702333,0.631667,7.666667,4.666667,18.333333,17.333333
7,8,2023-12-02,NaN,Stephen F. Austin,L (1 OT),74.0,79.0,21.0,55.0,0.382,...,0.426333,0.482333,0.386333,0.339000,0.674000,0.675333,11.000000,6.333333,21.000000,17.333333
8,9,2023-12-06,NaN,Northern Arizona,L,76.0,78.0,23.0,60.0,0.383,...,0.420333,0.535667,0.381333,0.432667,0.705333,0.703333,12.333333,7.333333,22.666667,20.666667
9,10,2023-12-10,NaN,Howard Payne,W,120.0,69.0,46.0,76.0,0.605,...,0.406667,0.507000,0.323000,0.414000,0.763333,0.723000,12.666667,7.333333,21.333333,23.333333
10,11,2023-12-17,NaN,UTEP,W,88.0,82.0,24.0,42.0,0.571,...,0.456667,0.437000,0.272667,0.339000,0.743667,0.658333,11.666667,7.333333,22.000000,25.000000
11,12,2023-12-21,@,Arkansas,L,73.0,83.0,28.0,72.0,0.389,...,0.519667,0.424667,0.348333,0.328667,0.713000,0.671333,8.333333,9.666667,22.333333,27.333333
12,13,2023-12-30,@,Western Kentucky,L,84.0,86.0,32.0,75.0,0.427,...,0.521667,0.434000,0.344000,0.373333,0.661000,0.666667,7.666667,8.666667,23.333333,24.333333
13,14,2024-01-06,NaN,Texas-Rio Grande Valley,W (1 OT),91.0,89.0,31.0,58.0,0.534,...,0.462333,0.481667,0.404000,0.383333,0.786000,0.693333,7.000000,8.000000,20.666667,21.000000
14,15,2024-01-11,@,Grand Canyon,L,64.0,74.0,24.0,59.0,0.407,...,0.450000,0.514000,0.361000,0.377667,0.763667,0.688333,8.000000,6.000000,19.666667,19.333333
15,16,2024-01-13,@,California Baptist,L,53.0,68.0,20.0,56.0,0.357,...,0.456000,0.501333,0.344333,0.320000,0.821667,0.714333,6.666667,6.333333,19.666667,18.666667
16,17,2024-01-18,@,Tarleton State,L,71.0,79.0,24.0,61.0,0.393,...,0.432667,0.467000,0.205333,0.301333,0.723667,0.772000,7.000000,5.333333,21.000000,19.333333
17,18,2024-01-20,NaN,UT Arlington,W,78.0,67.0,26.0,60.0,0.433,...,0.385667,0.470333,0.261000,0.329333,0.784667,0.726333,6.333333,4.000000,20.666667,16.333333
18,19,2024-01-25,NaN,Utah Tech,W,82.0,60.0,29.0,56.0,0.518,...,0.394333,0.417667,0.361000,0.305333,0.763333,0.642667,7.333333,7.000000,22.000000,18.000000
19,20,2024-01-27,NaN,Southern Utah,L,67.0,82.0,26.0,61.0,0.426,...,0.448000,0.442333,0.444333,0.263000,0.800667,0.558333,9.000000,7.333333,23.333333,18.333333
20,21,2024-02-01,NaN,Tarleton State,L (1 OT),73.0,76.0,28.0,57.0,0.491,...,0.459000,0.462000,0.361000,0.281333,0.707667,0.595000,8.666667,7.666667,24.000000,18.333333
21,22,2024-02-08,@,Seattle,L,52.0,75.0,17.0,68.0,0.250,...,0.478333,0.495667,0.298667,0.325000,0.644667,0.650000,8.000000,6.000000,21.666667,18.000000
22,23,2024-02-10,@,Utah Valley,L,45.0,74.0,14.0,58.0,0.241,...,0.389000,0.478333,0.261667,0.427333,0.617667,0.766667,7.000000,5.000000,19.666667,18.000000
23,24,2024-02-15,@,Texas-Rio Grande Valley,W,87.0,79.0,35.0,57.0,0.614,...,0.327333,0.465667,0.237000,0.431333,0.695333,0.780000,8.666667,6.666667,16.666667,16.666667
24,25,2024-02-17,@,Stephen F. Austin,W,63.0,62.0,20.0,54.0,0.370,...,0.368333,0.482333,0.266000,0.385000,0.745667,0.765000,8.000000,8.000000,17.333333,16.000000
25,26,2024-02-22,NaN,California Baptist,W,71.0,65.0,25.0,54.0,0.463,...,0.408333,0.533000,0.303000,0.370000,0.757667,0.669333,8.666667,8.333333,16.333333,16.333333
26,27,2024-02-24,NaN,Grand Canyon,W,79.0,73.0,23.0,60.0,0.383,...,0.482333,0.495333,0.396000,0.319667,0.765000,0.635667,7.333333,5.333333,18.666667,17.000000
27,28,2024-02-29,@,Southern Utah,W,77.0,68.0,31.0,59.0,0.525,...,0.405333,0.500667,0.384000,0.337333,0.793000,0.655333,7.666667,2.333333,18.000000,19.666667
28,29,2024-03-02,@,Utah Tech,W,86.0,79.0,31.0,65.0,0.477,...,0.457000,0.460667,0.506333,0.289667,0.802000,0.683333,5.666667,4.000000,18.666667,18.666667
29,30,2024-03-07,NaN,Seattle,W,64.0,59.0,25.0,59.0,0.424,...,0.461667,0.477000,0.497667,0.279667,0.821000,0.694667,7.666667,5.666667,17.666667,19.000000
30,31,2024-03-09,NaN,Utah Valley,L,67.0,74.0,24.0,50.0,0.480,...,0.475333,0.473333,0.474333,0.262000,0.783000,0.708333,10.000000,6.333333,16.666667,16.000000
31,32,2024-03-13,N,Stephen F. Austin,L,57.0,60.0,18.0,43.0,0.419,...,0.460333,0.481667,0.332000,0.333333,0.721333,0.700333,10.666667,5.333333,15.666667,18.000000
32,33,2024-03-19,N,Texas A&M-Corpus Christi,W,73.0,63.0,28.0,55.0,0.509,...,0.441000,0.454000,0.300000,0.386000,0.696667,0.652000,7.666667,6.333333,17.333333,20.000000
33,34,2024-03-20,@,Tarleton State,L,59.0,86.0,22.0,55.0,0.400,...,0.469333,0.400333,0.308667,0.342333,0.642333,0.585333,5.000000,8.333333,18.666667,20.000000

In [37]:
games_rolling = games.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols), include_groups=False)

In [38]:
games_rolling

                          g       date venue               opp       w/l  \
team
abilene christian 11993   4 2022-11-21     N      Wright State         L
                  11994   5 2022-11-22     N       Weber State         L
                  11995   6 2022-11-23     N      UC-Riverside         L
                  11996   7 2022-11-27     @  Northern Arizona         W
                  11997   8 2022-11-30   NaN    North American         W
...                      ..        ...   ...               ...       ...
youngstown state  11985  28 2024-02-17     @   Cleveland State         L
                  11986  29 2024-02-23     @         Milwaukee  W (1 OT)
                  11987  30 2024-02-25     @         Green Bay         W
                  11988  31 2024-02-28   NaN     Detroit Mercy         W
                  11989  32 2024-03-07   NaN   Cleveland State         L

                           tm  opp.1    fg   fga    fg%  ...  fg%_rolling  \
team                                                     ...
abilene christian 11993  61.0   77.0  25.0  58.0  0.431  ...     0.464000
                  11994  67.0   77.0  26.0  53.0  0.491  ...     0.473000
                  11995  65.0   76.0  22.0  60.0  0.367  ...     0.508333
                  11996  92.0   82.0  34.0  60.0  0.567  ...     0.429667
                  11997  93.0   46.0  31.0  68.0  0.456  ...     0.475000
...                       ...    ...   ...   ...    ...  ...          ...
youngstown state  11985  73.0   81.0  25.0  58.0  0.431  ...     0.404333
                  11986  84.0   80.0  32.0  78.0  0.410  ...     0.415667
                  11987  71.0   59.0  26.0  55.0  0.473  ...     0.412667
                  11988  69.0   55.0  26.0  61.0  0.426  ...     0.438000
                  11989  70.0   82.0  27.0  61.0  0.443  ...     0.436333

                         fg%.1_rolling  3p%_rolling  3p%.1_rolling  \
team
abilene christian 11993       0.409667     0.341333       0.251000
                  11994       0.476333     0.352000       0.367667
                  11995       0.459000     0.380333       0.338000
                  11996       0.511000     0.379667       0.372000
                  11997       0.472000     0.459000       0.372000
...                                ...          ...            ...
youngstown state  11985       0.426333     0.287667       0.401000
                  11986       0.469000     0.275667       0.344333
                  11987       0.434667     0.241667       0.281333
                  11988       0.443000     0.267667       0.233333
                  11989       0.380000     0.344667       0.258333

                         ft%_rolling  ft%.1_rolling  stl_rolling  \
team
abilene christian 11993     0.718667       0.698333    11.666667
                  11994     0.668667       0.671000    12.333333
                  11995     0.572667       0.739667    11.000000
                  11996     0.574333       0.819000     8.333333
                  11997     0.653000       0.850667     6.666667
...                              ...            ...          ...
youngstown state  11985     0.820667       0.730667     6.000000
                  11986     0.802000       0.736333     3.666667
                  11987     0.759333       0.776333     4.666667
                  11988     0.771333       0.785667     6.000000
                  11989     0.691667       0.758000     6.333333

                         stl.1_rolling  pf_rolling  pf.1_rolling
team
abilene christian 11993       8.666667   19.000000     18.666667
                  11994      10.666667   21.000000     16.333333
                  11995       8.333333   20.000000     15.000000
                  11996       7.666667   21.000000     15.333333
                  11997       4.666667   20.666667     16.666667
...                                ...         ...           ...
youngstown state  11985       3.000000   15.666667     21.333333
                  11986       3.666667   17.333333     20.333333
                  11987       5.333333   18.000000     21.666667
                  11988       5.666667   18.333333     20.000000
                  11989       6.000000   16.000000     17.333333

[22646 rows x 57 columns]

In [39]:
games_rolling = games_rolling.reset_index()

In [40]:
games_rolling

,team,level_1,g,date,venue,opp,w/l,tm,opp.1,fg,...,fg%_rolling,fg%.1_rolling,3p%_rolling,3p%.1_rolling,ft%_rolling,ft%.1_rolling,stl_rolling,stl.1_rolling,pf_rolling,pf.1_rolling
0,abilene christian,11993,4,2022-11-21,N,Wright State,L,61.0,77.0,25.0,...,0.464000,0.409667,0.341333,0.251000,0.718667,0.698333,11.666667,8.666667,19.000000,18.666667
1,abilene christian,11994,5,2022-11-22,N,Weber State,L,67.0,77.0,26.0,...,0.473000,0.476333,0.352000,0.367667,0.668667,0.671000,12.333333,10.666667,21.000000,16.333333
2,abilene christian,11995,6,2022-11-23,N,UC-Riverside,L,65.0,76.0,22.0,...,0.508333,0.459000,0.380333,0.338000,0.572667,0.739667,11.000000,8.333333,20.000000,15.000000
3,abilene christian,11996,7,2022-11-27,@,Northern Arizona,W,92.0,82.0,34.0,...,0.429667,0.511000,0.379667,0.372000,0.574333,0.819000,8.333333,7.666667,21.000000,15.333333
4,abilene christian,11997,8,2022-11-30,NaN,North American,W,93.0,46.0,31.0,...,0.475000,0.472000,0.459000,0.372000,0.653000,0.850667,6.666667,4.666667,20.666667,16.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22641,youngstown state,11985,28,2024-02-17,@,Cleveland State,L,73.0,81.0,25.0,...,0.404333,0.426333,0.287667,0.401000,0.820667,0.730667,6.000000,3.000000,15.666667,21.333333
22642,youngstown state,11986,29,2024-02-23,@,Milwaukee,W (1 OT),84.0,80.0,32.0,...,0.415667,0.469000,0.275667,0.344333,0.802000,0.736333,3.666667,3.666667,17.333333,20.333333
22643,youngstown state,11987,30,2024-02-25,@,Green Bay,W,71.0,59.0,26.0,...,0.412667,0.434667,0.241667,0.281333,0.759333,0.776333,4.666667,5.333333,18.000000,21.666667
22644,youngstown state,11988,31,2024-02-28,NaN,Detroit Mercy,W,69.0,55.0,26.0,...,0.438000,0.443000,0.267667,0.233333,0.771333,0.785667,6.000000,5.666667,18.333333,20.000000
22645,youngstown state,11989,32,2024-03-07,NaN,Cleveland State,L,70.0,82.0,27.0,...,0.436333,0.380000,0.344667,0.258333,0.691667,0.758000,6.333333,6.000000,16.000000,17.333333

In [41]:
games_rolling.index = range(games_rolling.shape[0])

In [42]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-05-01']
    test = data[data["date"] > '2023-05-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted = preds), index = test.index)
    precision = precision_score(test["target"], preds)
    accuracy = accuracy_score(test["target"], preds)
    return combined, precision, accuracy

In [43]:
combined, precision, accuracy = make_predictions(games_rolling, predictors + new_cols)

In [44]:
precision

0.6607142857142857

In [45]:
accuracy

0.6456110877782444

In [46]:
combined

       actual  predicted
24          0          0
25          0          1
26          1          0
27          1          0
28          0          0
...       ...        ...
22641       0          1
22642       1          0
22643       1          1
22644       1          1
22645       0          1

[11905 rows x 2 columns]

In [47]:
combined = combined.merge(games_rolling[["date", "team", "opp", "w/l"]], left_index=True, right_index=True)

In [48]:
combined

,actual,predicted,date,team,opp,w/l
24,0,0,2023-11-10,abilene christian,NC State,L
25,0,1,2023-11-14,abilene christian,Prairie View,L
26,1,0,2023-11-17,abilene christian,San Jose State,W
27,1,0,2023-11-19,abilene christian,Fordham,W
28,0,0,2023-11-20,abilene christian,Missouri State,L
...,...,...,...,...,...,...
22641,0,1,2024-02-17,youngstown state,Cleveland State,L
22642,1,0,2024-02-23,youngstown state,Milwaukee,W (1 OT)
22643,1,1,2024-02-25,youngstown state,Green Bay,W
22644,1,1,2024-02-28,youngstown state,Detroit Mercy,W
22645,0,1,2024-03-07,youngstown state,Cleveland State,L